spring:
  profiles:
    active:
    - dev
    
---

spring:
  profiles: dev #开发环境
  application:
    name: microservicecloudself-config-liuyc-dec

---

spring:
  profiles: test #开发环境
  application:
    name: microservicecloudself-config-liuyc-test
    